# Generated by Django 6.0.5 on 2026-05-30 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('average_attendance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assignment_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Course Analytics',
            },
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assignments_submitted', models.IntegerField(default=0)),
                ('assignments_pending', models.IntegerField(default=0)),
                ('courses_completed', models.IntegerField(default=0)),
                ('study_hours_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('ai_interactions', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student Analytics',
            },
        ),
    ]
