# Generated by Django 6.0.5 on 2026-05-18 05:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('Homework', 'Homework'), ('Project', 'Project'), ('Quiz', 'Quiz'), ('Essay', 'Essay'), ('Presentation', 'Presentation')], default='Homework', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('total_marks', models.IntegerField(default=100)),
                ('instructions', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('classes', models.CharField(blank=True, help_text='Comma-separated class names (e.g., 10A,10B)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('Notes', 'Notes'), ('PDF', 'PDF Document'), ('Video', 'Video'), ('Presentation', 'Presentation'), ('Coding', 'Coding Files'), ('Other', 'Other')], default='Notes', max_length=20)),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English'), ('Computer Science', 'Computer Science'), ('History', 'History'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Other', 'Other')], default='Other', max_length=50)),
                ('file', models.FileField(upload_to='learning_resources/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (e.g., YouTube)')),
                ('teacher_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(blank=True, help_text='Comma-separated class names (e.g., 10A,10B)', max_length=100)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Learning Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('address', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('class_name', models.CharField(default='10A', max_length=10)),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('Homework', 'Homework'), ('Exam', 'Exam'), ('Grade', 'Grade'), ('Attendance', 'Attendance'), ('General', 'General'), ('Event', 'Event')], max_length=50)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_url', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='school.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('marks', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='school.student')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('marks_obtained', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_marks', models.FloatField(default=100)),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Annual', 'Annual')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('Unit Test', 'Unit Test'), ('Mid-term', 'Mid-term'), ('Final', 'Final'), ('Quiz', 'Quiz')], max_length=20)),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('room_number', models.CharField(blank=True, max_length=10)),
                ('total_marks', models.IntegerField(default=100)),
                ('obtained_marks', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.student')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('class_name', 'day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='school.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(upload_to='submissions/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Resubmit', 'Resubmit Required')], default='Submitted', max_length=20)),
                ('marks_obtained', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True)),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('feedback_file', models.FileField(blank=True, null=True, upload_to='feedback/')),
                ('resubmission_date', models.DateTimeField(blank=True, null=True)),
                ('resubmission_file', models.FileField(blank=True, null=True, upload_to='resubmissions/')),
                ('is_late', models.BooleanField(default=False)),
                ('late_days', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='school.student')),
            ],
            options={
                'ordering': ['-submission_date'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
