# Generated by Django 6.0.5 on 2026-05-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layouts', models.JSONField(blank=True, default=dict, help_text='Stores lg, md, sm breakpoint layout arrays for react-grid-layout.')),
                ('visible_widgets', models.JSONField(blank=True, default=list, help_text='Ordered list of active widget keys.')),
                ('theme_preferences', models.JSONField(blank=True, default=dict, help_text='Stores theme (dark/light), mode, sidebarWidth, isSidebarCollapsed etc.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_layout',
            },
        ),
    ]
